name: Docker Image CI

on: workflow_dispatch

jobs:

  job11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  job2:

    runs-on: ubuntu-latest
    needs: job11

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
