
name: Build and Push Image to Docker Hub
#Event Trigger
on:
  push:
    branches: ["main"]
  pull_request:
   branches: ["main"]
#Jobs Define

jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rahatullahengineer  
          password: 123456789
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rahatullahengineer/rahat_2025:1
